# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('title_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('title_data', models.TextField(blank=True)),
                ('page_data', models.TextField(blank=True)),
                ('placeholders', models.TextField(blank=True)),
                ('plugins', models.TextField(blank=True)),
                ('plugin_instance', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
