# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-25 11:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('title_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('title_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('page_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('placeholders', django.contrib.postgres.fields.jsonb.JSONField()),
                ('plugins', django.contrib.postgres.fields.jsonb.JSONField()),
                ('plugin_instance', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
