# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-24 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version_history',
            name='page',
        ),
        migrations.RemoveField(
            model_name='version_history',
            name='title',
        ),
    ]
