# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-24 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_history', '0002_auto_20180524_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='version_history',
            name='page_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='version_history',
            name='title_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
